[package]
name = "FinalProject210"
version = "0.1.0"
edition = "2021"

[dependencies]
# Graph handling
petgraph = "0.6"

# File handling and parsing
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }

#error handling
anyhow = "1.0"
thiserror = "1.0"

#logging
log = "0.4"
env_logger = "0.10"

[dev-dependencies]
 
proptest = "1.0" # Property-based testing
quickcheck = "1.0" # Randomized testing
